services:
  db:
    image: postgres:16-alpine
    container_name: lms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lms
      - POSTGRES_PASSWORD=lms
      - POSTGRES_DB=lms
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms -d lms"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
  image: dpage/pgadmin4
  ports:
    - "8081:80"
  environment:
    PGADMIN_DEFAULT_EMAIL: admin@devmail.net
    PGADMIN_DEFAULT_PASSWORD: S3cure!Passw0rd    
  depends_on:
    - db

volumes:
  pgdata:
