version: '3.9'
services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@devmail.net
      - PGADMIN_DEFAULT_PASSWORD=S3cure!Passw0rd
    ports:
      - "8081:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - lmsnet

networks:
  lmsnet:
    external: true
    name: backend-lms-postgres_default

volumes:
  pgadmin-data:
