# ==== Common ====
server:
  shutdown: graceful

spring:
  application:
    name: backend-lms-postgres
  threads:
    virtual:
      enabled: true
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

logging:
  level:
    root: INFO
    com.example.lms: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true

# JWT Configuration
app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000  # 24 hours in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
